name: generate-markdown

on: [workflow_dispatch, push]

jobs:
  auto-update-readme:
      runs-on: ubuntu-latest
      steps:
        - uses: actions/checkout@v2
          with:
            ref: build-scripts
        - name: Markdown autodocs
          uses: dineshsonachalam/markdown-autodocs@v1.0.4
          with:
            output_file_paths: '[./README.md, ./docs/*.md]'
